# Generated by Django 3.2.4 on 2022-03-05 22:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('desc', models.CharField(max_length=500)),
                ('price', models.FloatField(default=0.0)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=2)),
                ('category', models.CharField(choices=[('PL', 'Plantas'), ('TS', 'T-Shirt'), ('TR', 'Trouser')], max_length=2)),
                ('img1', models.ImageField(default='', upload_to='ecomm/images')),
                ('img2', models.ImageField(default='', upload_to='ecomm/images')),
                ('img3', models.ImageField(default='', upload_to='ecomm/images')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('price', models.IntegerField()),
                ('address', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('date', models.DateField(default=datetime.datetime.today)),
                ('card_name', models.CharField(blank=True, max_length=200)),
                ('card_number', models.CharField(blank=True, max_length=20)),
                ('card_cvv', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecomm.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
