# Generated by Django 3.2.4 on 2022-03-05 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('SH', 'Shirt'), ('TS', 'T-Shirt'), ('TR', 'Trouser')], max_length=2),
        ),
    ]
