# Generated by Django 3.2.4 on 2022-03-05 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('PL', 'Plantas'), ('FL', 'Flores'), ('PB', 'Produtos Botânica')], max_length=2),
        ),
    ]
