# Generated by Django 3.2.4 on 2022-03-05 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0003_alter_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='size',
        ),
    ]
