# Generated by Django 3.2.4 on 2022-03-06 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomm', '0005_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='enabled',
            field=models.CharField(default='', max_length=20),
        ),
    ]
